spring:
  application:
    name: config-server
  cloud:
    config:
      server:
            git:
              uri: https://github.com/learning-up/spring-cloud.git
              searchPaths: cloud-config-repo
server:
  port: 8882
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.0.212:8883/eureka/
    instance:
          lease-expiration-duration-in-seconds: 30
          lease-renewal-interval-in-seconds: 10