server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8083/eureka/
#    healthcheck:
#        enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: cloud-simple-service