server:
  port: 8886

spring:
  application:
    name: hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8883/eureka/
    instance:
          lease-expiration-duration-in-seconds: 30
          lease-renewal-interval-in-seconds: 10