server:
  port: 8886

spring:
  application:
    name: hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin192.168.0.212:8883/eureka/
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    ip-address: 192.168.10.194 #IP有误，强行修改
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10