server:
  port: 8884

spring:
  application:
    name: zuul

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 30000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.212:8883/eureka/
  instance:
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 10

