server:
  port: 8083

eureka:
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 30000
  instance:
    hostname:
      localhost
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/