server:
  port: 8883

eureka:
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 10000
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone:  http://localhost:${server.port}/eureka/
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin